### PR TITLE
Replace filter_null with filter_args

### PR DESCRIPTION
**Pull request by LewisAJones**
This PR replaces `filter_null` with `filter_args`. This update increases filtering to remove arguments defined as FALSE to avoid unnecessary parameters being passed in the API query. Ideally this wouldn’t be an issue, but in some instances, some parameters on endpoints don’t seem to function as expected. For example: 

Doesn’t return adjacents 👍🏻 
https://macrostrat.org/api/columns?col_id=489&response=long

Returns adjacents 👍🏻 
https://macrostrat.org/api/columns?col_id=489&response=long&adjacents=TRUE

Also returns adjacents 👎🏻 
https://macrostrat.org/api/columns?col_id=489&response=long&adjacents=FALSE

### CODE REVIEW

**Comment by willgearty** [comment]
Are we sure there aren't any arguments across all of the endpoints that have "true" as the default and that we might want to set to "false"?

**Comment by LewisAJones** [comment]
This is what I was concerned about too, but from what I can see across endpoints, logical parameters are always FALSE by default, so excluding those parameters results in the same response. For example, `sf = FALSE` would still return a json even if left out the query.

**Comment by willgearty** [comment]
Well, for possible future needs, I would propose that you add two arguments to the function, one that controls whether NULL arguments are filtered, and one that controls whether FALSE arguments are filtered. Otherwise, it looks good to me!

**Comment by LewisAJones** [comment]
I agree with that! Just pushed some changes.

**Review by willgearty — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
